[style.description]
foreground = { rgb = { r = 248, g = 248, b = 242 } }
underline = false
bold = true
italic = false

[style.command_name]
foreground = { rgb = { r = 255, g = 121, b = 198 } }
underline = false
bold = false
italic = false

[style.example_text]
foreground = { rgb = { r = 80, g = 250, b = 123 } }
underline = false
bold = false
italic = false

[style.example_code]
foreground = { rgb = { r = 189, g = 147, b = 249 } }
underline = false
bold = false
italic = false

[style.example_variable]
foreground = { rgb = { r = 139, g = 233, b = 253 } }
underline = true
bold = false
italic = false

[display]
compact = false
use_pager = false

[updates]
auto_update = true
auto_update_interval_hours = 720

[directories]
